Repository openimsdk/openmeeting-server, pull requests merged in 2024-08, with the labels that each got.

#2 feat: user query extracted into interface
  go.mod
  go.sum
  internal/api/admin/router.go
  internal/api/mw/mw.go
  internal/api/router.go
  internal/api/user.go
  internal/rpc/meeting/convert.go
  internal/rpc/meeting/init.go
  internal/rpc/meeting/meeting.go
  internal/rpc/meeting/notification.go
  internal/rpc/user/user.go
  pkg/rpcclient/user.go
  pkg/rtc/callback.go
  pkg/rtc/livekit/callback.go
  pkg/rtc/livekit/define.go
  pkg/rtc/livekit/livekit.go
  pkg/rtc/rtc.go
  pkg/user/meeting.go
  pkg/user/user.go
Labels: size/L

#4 feat: optimize code
  pkg/rtc/livekit/livekit.go
Labels: size/M

#5 Branch/documentation to main
  .gitignore
  README.md
  README_zh_CN.md
  deployments/deployment.md
  deployments/deployment_zh_CN.md
Labels: size/L

#6 fix to main branch
  HOW_TO_SETUP_LIVEKIT.md
  internal/rpc/meeting/convert.go
  internal/rpc/meeting/meeting.go
  internal/rpc/user/user.go
  pkg/common/cachekey/user.go
  pkg/common/storage/cache/redis/user.go
Labels: size/M

#9 remove user id when request for user registeration
  README.md
  README_zh_CN.md
  go.mod
  go.sum
  internal/api/admin/admin.go
  pkg/common/cachekey/user.go
  pkg/common/storage/cache/redis/user.go
  pkg/common/storage/cache/user.go
  pkg/common/storage/controller/user.go
  pkg/common/xlsx/definition/definition.go
  pkg/rtc/livekit/livekit.go
Labels: size/M

#11 Gen user id issue 8
  config/discovery.yml
  config/livekit.yml
  config/mongodb.yml
  config/openmeeting-admin-api.yml
  config/openmeeting-api.yml
  config/openmeeting-rpc-meeting.yml
  config/openmeeting-rpc-user.yml
  config/share.yml
Labels: size/S

#13 feat: create workflows in open meeting server
  .github/.codecov.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-build-test.yml
  .github/workflows/issue-translator.yml
  docker-compose.yml
  magefile.go
Labels: size/L

#15 update config
  README.md
  README_zh_CN.md
  components/livekit/config/livekit.yml
Labels: size/XS
